name: Daily Fixture Fetch

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 8:00 AM Kenya time
  workflow_dispatch:     # Allows manual trigger in GitHub

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run fetchFixtures script
        run: node fetchFixtures.js
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          API_KEY: ${{ secrets.API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
